### ISSUE TITLE
RESPOSTAS?

### ISSUE THREAD

**Issue by CaioLemes** [CaioLemes/Projeto-Locadora#11]
Trabalho para dia 25/09 pessoal....

**Comment by CampeonatoJJJE** [comment]
o Jean ficou de fazer essa parte, e ele faltou. Nós ficamos com a parte de assessorar o outro grupo.
Mas fique tranquilos, o trabalho será entregue dentro do prazo. <3

**Comment by bmarchete** [comment]
Não entendi bem a conversa! O Jean ia fazer sozinho as respostas? O resto do grupo vai só acessorar? Humm, isso me cheira 💩
