### ISSUE TITLE
Estou divagando? A modelagem está correta?

### ISSUE THREAD

**Issue by bmarchete** [CaioLemes/Projeto-Locadora#12]
@CaioLemes Talvez eu esteja divagando, mas na sua modelagem, uma pessoa só pode alugar um filme por vez? Isso não seria absurdo? O que vocês acham disso @CampeonatoJJJE

**Comment by CampeonatoJJJE** [comment]
Realmente, uma pessoa pode alugar quantos filmes quiser por vez.

**Comment by CaioLemes** [comment]
Nós tentamos achar algum jeito de arrumar este "erro" no DB, porém acabamos não achando uma forma de fazer isso. Vamos considerar que para cada filme alugado, foi criado um aluguel diferente, mesmo que seja para o mesmo cliente.
