### ISSUE TITLE
Erro no código de criação

### ISSUE THREAD

**Issue by CampeonatoJJJE** [CaioLemes/Projeto-Locadora#2]
Altere seu código de criação do banco pois  a segunda linha está dando erro
```sql
use locadora
```

**Comment by CampeonatoJJJE** [comment]
E a tabela aluguel também possui erro na foreign key

**Comment by CaioLemes** [comment]
Erros corrigidos, os novos arquivos já estão disponiveis.
Obrigado por nos avisar!
